[build]
base = "frontend"
command = "npm run build"
publish = "build"

[build.environment]
REACT_APP_API_URL = "https://lead-scoring-backend.onrender.com"

[build.environment.production]
REACT_APP_API_URL = "https://lead-scoring-backend.onrender.com"
